/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import UI.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author UPULI - GAYASHIYA
 */
public class Registration extends javax.swing.JFrame {

   String gender;
    
    public Registration() {
        initComponents();
        setLocationRelativeTo(null);
    }
         Connection con;
        PreparedStatement insert;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_regi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcon = new javax.swing.JTextField();
        lblname1 = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblname4 = new javax.swing.JLabel();
        lblname6 = new javax.swing.JLabel();
        lblname7 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        lblname8 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        txtln = new javax.swing.JTextField();
        txtfn = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        lblname9 = new javax.swing.JLabel();
        txt_clr = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblname3 = new javax.swing.JLabel();
        txtrid = new javax.swing.JTextField();
        d_bdy = new com.toedter.calendar.JDateChooser();
        d_regi = new com.toedter.calendar.JDateChooser();
        lblname5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        lbl_regi.setBackground(new java.awt.Color(255, 255, 255));
        lbl_regi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_regi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_regi.setText("Student Registration");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/left-1.1s-60px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(lbl_regi, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(36, 36, 36)
                .addComponent(lbl_regi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 130));

        txtcon.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(txtcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 300, 50));

        lblname1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname1.setText("First Name :-");
        jPanel1.add(lblname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        lblname2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname2.setText("Last Name :-");
        jPanel1.add(lblname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        lblname4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname4.setText("Gender  :-");
        jPanel1.add(lblname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 40));

        lblname6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname6.setText("Address :-");
        jPanel1.add(lblname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 140, 40));

        lblname7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname7.setText("Birthday :-");
        jPanel1.add(lblname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 40));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        lblname8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname8.setText("Contact Number :- ");
        jPanel1.add(lblname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, 40));

        txtadd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 300, 140));

        txtln.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(txtln, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 310, 40));

        txtfn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(txtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 310, 40));

        btn_Submit.setBackground(new java.awt.Color(204, 204, 204));
        btn_Submit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_Submit.setText("Submit ");
        btn_Submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 280, 50));

        lblname9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname9.setText("Registration Date :-");
        jPanel1.add(lblname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 180, 40));

        txt_clr.setBackground(new java.awt.Color(204, 204, 204));
        txt_clr.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txt_clr.setText("Reset");
        txt_clr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clrActionPerformed(evt);
            }
        });
        jPanel1.add(txt_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 710, 140, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 20, 540));

        lblname3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname3.setText("Admission for :-");
        jPanel1.add(lblname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 160, 40));

        txtrid.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(txtrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 310, 40));
        jPanel1.add(d_bdy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 250, 40));
        jPanel1.add(d_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 250, 40));

        lblname5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblname5.setText("Admission No:-");
        jPanel1.add(lblname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grade 12/13 Advanced Level Class");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 340, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Grade 6 to 9");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 340, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Grade 10 ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 340, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grade 11 Ordinary Level Class");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 340, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Grade 1 to 5 ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 340, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
//     submit details and back to login

         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/schooldb","root",""); 
            insert = con.prepareStatement("insert into stu_regi(admission_no,firstname,lastname,bday,gender,regi_dy,contact,address)values(?,?,?,?,?,?,?,?)");  
            insert.setString(1, txtrid.getText());
            insert.setString(2, txtfn.getText());
            insert.setString(3, txtln.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(d_bdy.getDate());
            insert.setString(4,date);
          
           if(male.isSelected()){
               gender = "Male";}
           if(female.isSelected()){
               gender = "Female";}
            insert.setString(5, gender);
          
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String date2 = sdf1.format(d_regi.getDate());
            insert.setString(6,date2);
           
           insert.setString(7, txtcon.getText());
           insert.setString(8, txtadd.getText());
           insert.executeUpdate();
            JOptionPane.showMessageDialog(null, "Submit Sucessfully! Welcome to School DataBase");
            
           
           
         }
             catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
      
              
              
                   
//           String usertype;
//           usertype = utype.getSelectedItem().toString();
//           insert.setString(7, usertype);
           
      
          
          
          

    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_femaleActionPerformed

    private void txt_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clrActionPerformed
       txtrid.setText("");
       txtfn.setText("");
       txtln.setText("");
 //      d_bdy.setDate("");
//       d_regi.setDate("");
       txtcon.setText("");
       txtadd.setText("");
       buttonGroup1.clearSelection();
       
    }//GEN-LAST:event_txt_clrActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
    
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // open grade 1_5 panel:
        
        Grade1_5 g15 = new Grade1_5();
        g15.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // open grade 6_9 panel:
        
        Grade6_9 g69 = new Grade6_9();
        g69.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //open grade 10 panel:
        
        Grade10 g10 = new Grade10();
        g10.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       
        Grade10 g10 = new Grade10();
        g10.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //open grade12/13 pnel
        
        Grade12 g12 = new Grade12();
        g12.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser d_bdy;
    private com.toedter.calendar.JDateChooser d_regi;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_regi;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblname4;
    private javax.swing.JLabel lblname5;
    private javax.swing.JLabel lblname6;
    private javax.swing.JLabel lblname7;
    private javax.swing.JLabel lblname8;
    private javax.swing.JLabel lblname9;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton txt_clr;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtfn;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtrid;
    // End of variables declaration//GEN-END:variables
}
